### ISSUE TITLE
zqsn inout

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/Icepack#103]
zqsn should be intent(inout) in icepack_therm_vertical.F90, subroutine init_vertical_profile

**Comment by dabail10** [comment]
Is this true in CICE5.1.2 as well? All that happens here is that zqsn is set to trcrn(:,:,nt_qsno,:,:). I guess Icepack does not have trcrn?

Dave

**Comment by eclare108213** [comment]
It appears to be fine in v5.1.2.  In Icepack (and now CICE), depending on how the conditional is evaluated, zqsn might be used before it is defined in the subroutine.
e

**Comment by eclare108213** [comment]
this one probably will change the answers

**Comment by apcraig** [comment]
Fixed in PR #132
