### ISSUE TITLE
BGC output

### ISSUE THREAD

**Issue by duvivier** [CICE-Consortium/Icepack#105]
Please check that the documentation about BGC output in CICE is correct in the Icepack documentation:
https://cice-consortium.github.io/Icepack/user_guide/ug_implementation.html#biogeochemistry-history-fields

**Comment by eclare108213** [comment]
I suggest you remove the word "Note" at the beginning and this part of the text:

> The biogeochemical history fields specified in icefields_bgc_nml are written when ‘x’ is replaced with a time interval: step (‘1’), daily (‘d’), monthly (‘m’), or yearly (‘y’). Several of these flags turn on multiple history variables according to the particular ecosystem prescribed in icepack_in. For example, biogeochemical fluxes from the ice to ocean will be saved monthly in the history output if

> f_fbio = 'm'

> However, only the biogeochemical tracers which are active will be saved. This includes at most fNit nitrate, fAm ammonium, fN algal nitrogen, fDOC dissolved organic carbon, fDON dissolved organic nitrogen, fFep particulate iron, fFed dissolved iron, fSil silicate, fhum humic matter, fPON passive mobile tracer, fDMS DMS, fDMSPd dissolved DMSP and fDMSPp particulate DMSP.

**Comment by duvivier** [comment]
Fixed with PR #104
