### ISSUE TITLE
Makefile conditionals within targets

### ISSUE THREAD

**Issue by mattdturner** [CICE-Consortium/Icepack#108]
The new makefile, after adding CCE, GNU, and PGI compilers includes a conditional within some of the targets
```
	@if [ "$(COMPILER)" == "cray" ] || [ "$(COMPILER)" == "pgi" ]; then \
	  mv $*.i $*.f; \
	fi
```
This is because the CCE and PGI compilers output a .i file when running through the preprocessor.  There is likely a way with each compiler to alter the output file extension so that this branch is not required.

**Comment by apcraig** [comment]
This is fixed in PR#113.  Got rid of the separate preprocessing step, now preprocesing as part of compilation.
