### ISSUE TITLE
combine constants and parameters

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/Icepack#110]
Move contents of icepack_constants.F90 into icepack_parameters.F90.    
Move all default settings for icepack parameters into icepack_parameters.F90.    
(note that there are some driver-specific namelist settings that should remain only in icedrv*)
Check that icedrv queries icepack to get the default values, then reads namelist and updates those parameters, then (re)sets icepack's values.
Check query/init for tracers, bgc, similarly.

**Comment by eclare108213** [comment]
Addressed in PR #109 #111 #112 #116 
We still need to check the query/init implementation for tracers.

**Comment by duvivier** [comment]
References to icepack_constants.F90 taken out of documentation with PR #139
