### ISSUE TITLE
Version hardcoded in Documentation

### ISSUE THREAD

**Issue by apcraig** [CICE-Consortium/Icepack#115]
In section 1.3, file doc/source/intro/major_updates.rst.  Maybe we can just refactor a bit and call the section something like "separation of Icepack from CICE" and say this happened after CICE5 without specifying any specific versions?  

Or is this really going to be an ongoing "ChangeLog" that will provide an overview of changes since the start of Icepack?   If so, maybe that belongs in an appendix.

So, maybe have section 1.3 be an overview of when and why Icepack was separated from CICE.  And maybe create a new appendix that summarizes changes in Icepack since CICE.5 that can be an ongoing log.

**Comment by apcraig** [comment]
For instance, appendix B here, http://www.cerfacs.fr/oa4web/oasis3-mct_3.0/oasis3mct_UserGuide.pdf keeps track of changes from the start, but does not break it out by each version.  That's one example.  Another would be to actually track changes with each revision which I think is more common and probably something we should consider.  See, for instance, https://www.mozilla.org/en-US/firefox/releases/ but we'd just keep that info in a single appendix with a section associated with each release and have it accumulate.

**Comment by eclare108213** [comment]
Good point.  I would like this section to give and overview of what we did and why, to create Icepack.  Let's put the details in the release notes pages next to the tarballs, as releases come out (see https://github.com/CICE-Consortium/CICE-svn-trunk/releases).

**Comment by eclare108213** [comment]
Maybe we can keep a running log of important changes somewhere, since the last numbered release?

**Comment by eclare108213** [comment]
A running log has been added at 
https://github.com/CICE-Consortium/Icepack/wiki/Recent-changes
