### ISSUE TITLE
exponential underflows in dEdd shortwave

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/Icepack#118]
Some compilers are complaining about underflows in the shortwave calculation.  These are coming from exponentials with very small arguments.  The current code to get rid of those values does not avoid their being calculated in the first place:
>  argmax = 10.
> exp_min = exp(-argmax)
> f = max(exp(-A), exp_min)          ! exp(-A) is what we are trying to compute

We should do this instead:

> argmax = 10.
> exp_min = min(argmax, A)
> f = exp(-exp_min)

This type of calculation occurs in 3 places in icepack_shortwave.F90.
I expect this to change the answers (nonBFB).

**Comment by apcraig** [comment]
I will take this on as one of my next tasks, after a couple other tasks....

**Comment by apcraig** [comment]
I've implemented this on a branch and am testing, PR soon.

**Comment by eclare108213** [comment]
Fixed in PR #127
