### ISSUE TITLE
Abort with invalid cdn_atm_ratio_n

### ISSUE THREAD

**Issue by apcraig** [CICE-Consortium/Icepack#125]
The code aborts in merge_fluxes for sets=debug,dyn with gnu.  In that case, atmbndy="constant" and cdn_atm_ratio_n is never set but it is used.

The calling sequence is something like 

icepack_therm_vertical.F90, icepack_step_therm1 defines cdn_atm_ratio_n locally
icepack_step_therm1 calls icepack_atm_boundary with cdn_atm_ratio_n as argument
icepack_atm_boundary sets cdn_atm_ratio_n when atmbndy is NOT set to "constant"
icepack_step_therm1 calls merge_fluxes and cdn_atm_ratio_n is passed in and used

If someone helps me figure out what to do, I can implement and test it.

**Comment by eclare108213** [comment]
Please initialize Cdn_atm_ratio_n = c1 in icepack_atm_boundary.  
Cdn_atm can be removed from atm_boundary_const.
Thx

**Comment by apcraig** [comment]
If Cdn_atm is remove from atm_boundary_const, does it need to be set to 1.0 by default in icepack_atm_boundary with Cdn_atm_ratio_n or will it be set outside in cases where atmbndy=constant?
