### ISSUE TITLE
ice_brine exception

### ISSUE THREAD

**Issue by apcraig** [CICE-Consortium/Icepack#129]
Hitting another error with bgc in ice_brine.F90,

  write(99,*) subname,' tcx3',-darcy_coeff, (-darcy_coeff/bphi_min*dt)
  call flush(99)
               hbrocn_new = hbrocn*exp(-darcy_coeff/bphi_min*dt)

The exp is blowing up with gnu and debug flags.  The last two values before blowup are

 (update_hbrine) tcx3  -1.1392520136377392E-009  -2.3407096177064297E-003
 (update_hbrine) tcx3 -0.56199991572839070       -3597.1318270922047     

The last set of values are creating problems with exp(-3597.).  I can keep adding checks for exps that are too large or too small, but if those values are not physical, then there are underlying issues that need to be fixed.  Thoughts?

**Comment by njeffery** [comment]
@apcraig   Which test are you running?

**Comment by njeffery** [comment]
@apcraig:  I've looked a bit closer at the code.  There is nothing physically wrong the exp(-3597).  The solution hbrocn_new = 0 is valid.  Go ahead and add an if  "darcy_coeff/bphi_min*dt" is larger than numerically feasible,  hbrocn_new = 0.

**Comment by apcraig** [comment]
I have implemented an underflow fix that is commented out in PR #126 and will change answers.  That fix needs some review.  At the present time, this is still causing some cases to underflow when testing with the debug flags.  But the science should be ok with the underflow as we underflow to zero by design.

**Comment by eclare108213** [comment]
@apcraig I think you should go ahead and fix this in Icepack, and then check it in CICE using the quality control test.  There is another exp() immediately below the one you fixed and commented out, which could be causing the other underflows.  I think what you're doing is correct.  
As you're doing this, please record all the steps you took to make the change in icepack and then do the regular and QC tests in cice, so the rest of us will know how to handle such a case.  Thx

**Comment by apcraig** [comment]
Will do.  I haven't done the QC tests before.  Is there documentation or scripts?  thanks.

**Comment by eclare108213** [comment]
I think @mattdturner put it into the testing scripts for cice.  Maybe -qc.  I ran it but didn't get as far as plotting the output.  It is documented in the sphinx (cice) testing section, I believe.

**Comment by apcraig** [comment]
fixed with PR #158
