### ISSUE TITLE
cannot find entry symbol _start

### ISSUE THREAD

**Issue by dabail10** [CICE-Consortium/Icepack#130]
NAG is giving this message because there is no "program main" anywhere. Do we want this?

**Comment by eclare108213** [comment]
I don't think we care about this one.    Do we?
Would it be fixed by changing the program name (in icedrv_MAIN.F90) to 'main'?  That's easy enough, and I'm not totally wed to 'program icedrv'.

**Comment by apcraig** [comment]
I think this is a bit too much.  I'm fine if we want to change it, but I don't think we should.

I have not worked with NAG before.  Is our goal to get rid of all warnings?  If so, we should do it.  If not, then I think we should focus on the important ones first.

**Comment by dabail10** [comment]
I agree, I was just curious. I can easily change it to "main" though. I'm working my way through the NAG warnings and trying to focus on the dummy arguments in subroutines or unused locals. However, I just thought I should bring this one up.

Dave

**Comment by eclare108213** [comment]
And I'm fine with that too.  Keep icedrv
