### ISSUE TITLE
Call to remap_zbc

### ISSUE THREAD

**Issue by dabail10** [CICE-Consortium/Icepack#131]
This looks like a bug, but @njeffery can confirm this is the expected behaviour. So, the call to remap_bgc normally has ntrcr as the first argument. However, it is not actually used in that subroutine. The next two arguments are nlyrn (number of ice layers) and it (tracer index in top layer).  

            elseif (scale_bgc .and. ktherm == 2) then
               trtmp(:) = c0
               do n = 1,ncat
                  call remap_zbgc(nilyr, nilyr,    &
                                  1,                          &
                                  sicen(:,n),       trtmp,    &
                                  0,                nblyr+1,  &
                                  c1,               c1,       &
                                  cgrid(2:nilyr+1),           &
                                  igrid(1:nblyr+1),           &
                                  sicen(1,n)                  )
                  if (icepack_warnings_aborted(subname)) return

                  do mm = 1,nbtrcr
                  do k = 1, nblyr + 1
                     trcrn(bio_index(mm)+k-1-ntrcr_o,n) =   &
                          (trtmp(k)/sss*ocean_bio_all(bio_index_o(mm)))
                     trcrn(bio_index(mm)+nblyr+1-ntrcr_o:bio_index(mm)+nblyr+2-ntrcr_o,n) = c0 ! snow
                  enddo  ! k
                  enddo  ! mm
               enddo     ! n

**Comment by njeffery** [comment]
The first argument is a carry-over from when the size of the remapped tracers was needed in the declaration of the subroutine.  So,  it's no longer needed and can be removed. I know the call appears in icepack_zbgc.F90 but potentially other subroutines like icepack_algae.F90.


________________________________

**Comment by dabail10** [comment]
I'm more concerned about this particular instance of the call to remap_zbgc. Normally it is called with ntrcr, nilyr, and then a tracer number like nt_sice. Here it is called with nilyr, nilyr, and 1.

Dave

**Comment by dabail10** [comment]
Ok. Sounds good. I am removing the first argument, ntrcr to all of the calls to remap_bgc.
