### ISSUE TITLE
Bug in mushy layer?

### ISSUE THREAD

**Issue by dabail10** [CICE-Consortium/Icepack#133]
I noticed calls like this in two_stage_solver_snow and two_stage_solver_nosnow. In the subroutine for these, it has the arguments of Tsf0, zqsn0, zqin0, zSin0, zTsn0, and zTin0.

Then just before the call to the picard solver you have:

       if (fcondtop - fsurfn < ferrmax) then

          ! solution is consistent - have solution so finish
          return

       else

          ! solution is inconsistent - resolve assuming other surface condition
          ! assume surface is cold
          fcondtop1 = fcondtop
          fsurfn1   = fsurfn

         ! reset the solution to initial values
          Tsf  = Tsf0
          zqsn = zqsn0
          zqin = zqin0
          zSin = zSin0

          ! solve the system for melting and snow
          call picard_solver(nilyr,    nslyr,    &
                             .true.,   .false.,  &
                             Tsf,      zqsn,     &
                             zqin,     zSin,     &
                             zTin,     zTsn,     &

...

So, here is a dumb question for Adrian Turner. Why do you only reset Tsf, zqsn, zqin, and zSin, but not  zTsn and zTin? The NAG compiler is complaining about unused variables here. So, I just wanted to make sure they are not supposed to be used.

Dave

**Comment by eclare108213** [comment]
I don't understand what is unused, where?  zTin and zTsn are output from the thermodynamic calculation, so they don't need to be reset -- their values would get overwritten anyhow.

**Comment by dabail10** [comment]
So, sorry I wasn't clear. The two subroutines two_stage_solver_snow and nosnow receive 12 inputs which are Tsf, Tsf0, zqsn, zqsn0, zqin, zqin0, zSin, zSin0, zTsn, zTsn0, zTin and zTin0. Just before the call to the picard_solver, some of these are reset to the "initial" value with the 0. However, in some cases they are not reset to the "0" value and hence are never used in the subroutines. So in two_stage_solver_snow, zTin0 and zTsn0 are not used. In two_stage_solver_nosnow, zQsn0, zTin, and zTsn0 are not used.

**Comment by eclare108213** [comment]
Adrian has not responded.  I think it is correct as written, and the unused variables can be removed.  We have a record of it here if the issue comes up again.
