### ISSUE TITLE
Convergence code warning

### ISSUE THREAD

**Issue by dabail10** [CICE-Consortium/Icepack#148]
The convergence code that reads in the Lindsay SHEBA opening/closing data is working and interpolating the data correctly. However, the simulations with this code have some odd behaviour that we have not figured out yet. So, use this code with caution. We would love for the Icepack users to help us out with this!

**Comment by eclare108213** [comment]
Runs using the ‘clim’ forcing type without the convergence data all have a jump in ice area close to Oct 1.  This is when the air temperature suddenly gets a lot colder, and the shortwave is also decreasing precipitously then. The new ice is thin so the average ice thickness decreases at the same time.  There’s a big bump in congelation ice at abut the same time, presumably freezing onto the bottom of the new frazil ice (starting in the next time step).  The exponential change in freezing rate as the ice gets thicker is nicely apparent!

The convergence data is daily, and I wouldn’t expect it to be consistent with a sudden freeze-up on Oct 1.  But looking at the data, I don’t see any particular change in opening/closing associated with freeze-up.  It’s a lot more variable in October but I guess that could be a series of storms coming through.

I think the reason that this data amplifies the signal is that it’s producing more open water in the summer than is produced in the regular runs by thermodynamic melting, which amplifies the albedo feedback, so the ice area and thickness decrease more over the summer.  Then the freeze-up happens in a flash.

We can talk about whether the way new frazil volume is partitioned between area and thickness during freeze-up is appropriate — that’s a science project.  (That’s also one of the 2 tuning knobs in MPI’s super-simple sea ice model.) 

There are a couple of other blips in many of the fields in the summer, which seem to be associated with abrupt changes in top melt.  We might want to look more closely at what’s going on there.

The outgoing longwave field was surprising at first glance.  I would expect it to look more like the surface temperature field.  However, in the diagnostic output, flwout is sum(flwout * aice) over the categories, so we see the effects of ice area in it — decreasing values in spring, increases later as the remaining ice warms, then a big decrease when the ice surface gets cold after aice has reached 1.  

Sensible heat is weird too, but in this configuration (ice + slab ocean), it is the “free variable” that takes up whatever residual is left from the thermodynamic balance.  Sensible heat actually looks better in the case with the convergence data than without it — there’s some sort of oscillation in the case without, which definitely needs scrutiny.  I’ll make an issue for that separately.

At any rate, I think this test is doing what is expected of it.  The model has parameterizations in it now that have abrupt changes built in, particularly associated with ice/no-ice/pond/snow albedo differences.  Therefore the simulation at any given grid point isn’t particularly smooth, and maybe we need to look at that more closely too — another science project.
