### ISSUE TITLE
timeseries fonts for plots

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/Icepack#150]
The timeseries.csh script generates this error when making plots on pinto, resulting in tiny fonts.  Can this be fixed?

     Could not find/open font when opening font "arial", using internal non-scalable font

**Comment by mattdturner** [comment]
https://github.com/CICE-Consortium/Icepack/pull/164 attempts to resolve this.  The script now looks at the available fonts on the server, and will choose an Arial, Times, or Courier font (I can add additional fonts to the list if necessary, but all servers I have access to have one of those 3 available).

**Comment by eclare108213** [comment]
See PR #164 
The font issue was not fixed, but the grid cell info was added to the title.  I'll leave this as an active issue to be addressed later but remove it from the project list for release.
