### ISSUE TITLE
Finalize release documentation

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/Icepack#153]
- [x] Update doc/source/conf.py version/release
- [x] Generate and post html and pdf documentation
    Update pdf document to be carried with code
- [x] Create release notes 
- [x] Commit and push final changes to master including, at least,    
   doc/source/conf.py
   columnphysics/version.txt    
   updated pdf
-  [Tag release] 
- [x] Move release notes from https://github.com/CICE-Consortium/Icepack/wiki/Recent-changes to https://github.com/CICE-Consortium/Icepack/releases 
- [x]  Add links in appropriate places on github where to find the release and tar file
Pages containing a link to the release:    
https://github.com/CICE-Consortium/Icepack/wiki/Recent-changes    
https://github.com/CICE-Consortium/Icepack/blob/master/README.md (not specific)    
https://github.com/CICE-Consortium/Icepack/releases    
- [x]  Post science results as needed

**Comment by duvivier** [comment]
I updated conf.py with PR #161. I also pushed the HTML with PR #162 . There *may* be changes to the HTML still, though I don't know what they might be. Please let me know if I should go ahead and make the PDF and do a PR for that. As soon as that's done we can check off the second item and make progress on the fourth.

I also tested the wiki and README.md pages to make sure all the links work. They do all work. I did not add the links for the tarball since I'm not sure what exactly the path will be.

**Comment by duvivier** [comment]
I just added the PDF corresponding to the code and changes for PR #161 and #162. We can modify it if further changes become necessary, but I think we are close.

**Comment by eclare108213** [comment]
@duvivier I think this is all done.  I'm creating some plots of "science results" now.  In the meantime, could you look through the wikis for links to https://github.com/CICE-Consortium/Test-Results and point them instead to https://github.com/CICE-Consortium/Test-Results/wiki?  That's more direct.
Thanks!

**Comment by eclare108213** [comment]
Plots of output are here:
https://github.com/CICE-Consortium/Icepack/wiki/Sample-output

**Comment by duvivier** [comment]
Elizabeth, I had my talk this afternoon, so I just saw these requests and the release notification. Do you still want me to check the wiki links? As far as I could see right now it looked like everything was done and looking good! :)

**Comment by eclare108213** [comment]
@duvivier I fixed some of the links, maybe most/all of them.  If we come across any more, we can fix them then -- no need to search for them now.  Thanks!
