### ISSUE TITLE
"functional release"

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/Icepack#156]
Define the Icepack v1 release as a “functional release” — it runs, doesn't crash the model, passes various tests, and requires further work to establish its scientific validity.   In general, we do not encourage users to use any of the Consortium's model configurations for “science” — our test configurations are okay for model development.   Sea ice models to be evaluated from a physical standpoint in a coupled system because simplified configurations do not necessarily represent what’s actually happening in the fully coupled system. 

This needs to be added to the sphinx docs in section 3.5, maybe under the heading "Interpretation of results", and we should put it on a wiki page too if there's an appropriate place for it.

**Comment by duvivier** [comment]
I just defined this in the wiki under the release information and have added it to the sphinx documentation.
