### ISSUE TITLE
update wikis for readthedocs

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/Icepack#185]
update wikis (and elsewhere) to point to documentation on readthedocs instead of github.io, and edit documentation regarding how to use sphinx and readthedocs

**Comment by duvivier** [comment]
I have updated the wiki main page and added a page on documentation in general. We will still need to update the documentation itself to add a "how to use readthedocs" section and remove a bunch of the "how to use sphinx" stuff.
https://github.com/CICE-Consortium/Icepack/wiki
https://github.com/CICE-Consortium/Icepack/wiki/Icepack-Documentation

**Comment by duvivier** [comment]
Added how to use readthedocs to the documentation and incorporated as part of PR #187 .
