### ISSUE TITLE
Clean up Icepack /doc/ file

### ISSUE THREAD

**Issue by duvivier** [CICE-Consortium/Icepack#186]
With new readthedocs ability, we need to clean up the /doc/ directory. 

@eclare108213 can the following files be removed? 
Icepack-v1.0.0.pdf  --> we're moving to readthedocs, so I think we want to remove this old version, right?
DocForChanges.pdf  --> this is how people gave you changes to the column package. I think it's outdated now with the Pull Request workflow.
DocForChanges.rtf
ACMECollabAgreement_CICE_Hunke_Jul2015.pdf --> do we need this for the consortium?

Possible files we could remove:
I need to determine if these are necessary with readthedocs or if they could be removed as well.
make.bat
Makefile

**Comment by eclare108213** [comment]
> Icepack-v1.0.0.pdf --> we're moving to readthedocs, so I think we want to remove this old version, right?

yes
> DocForChanges.pdf --> this is how people gave you changes to the column package. I think it's > outdated now with the Pull Request workflow.
> DocForChanges.rtf

You can remove these.  They might still be useful, but I have copies if we need to bring them back into service. 
> ACMECollabAgreement_CICE_Hunke_Jul2015.pdf --> do we need this for the consortium?

No, this can be removed now.
Thanks!

**Comment by duvivier** [comment]
It looks like we could remove make.bat, Makefile, and .DS_Store from the /docs/ directory and readthedocs still works like we'd expect. However, use of Sphinx offline will not be possible without make.bat and Makefile. Do we still want to keep these files, just in case people want to use Sphinx instead of readthedocs?
@eclare108213 @apcraig @dabail10 , your input would be appreciated. I'm leaning toward keeping them, but want to hear other opinions.

**Comment by anders-dc** [comment]
FWIW, `.DS_Store` files are [auxiliary files for macOS](https://en.wikipedia.org/wiki/.DS_Store), and contain information like icons, etc. They have no place in these repositories, so I recommend deleting them and adding them to the `.gitignore` file.

**Comment by apcraig** [comment]
We should keep any files needed to build the documentation outside readthedocs.  I think it will be useful to continue to support this approach, at least for now.

**Comment by duvivier** [comment]
Okay, agreed that we should keep them. 

I have also added PR #189 to remove the .DS_Store file that somehow missed our scans. I have also added .DS_Store files to the CICE/.gitignore file and removed them from that repo as well.
