### ISSUE TITLE
zqsn initialization

### ISSUE THREAD

**Issue by dabail10** [CICE-Consortium/Icepack#191]
This code in init_vertical_profile has changed.

        if (hslyr > hs_min/rnslyr .and. heat_capacity) then
            ! zqsn < 0
            Tmax = -zqsn(k)*puny*rnslyr / &
                 (rhos*cp_ice*vsnon)
         else
            zqsn  (k) = -rhos * Lfresh
            Tmax = puny
         endif

zqsn(k) used to be initialized to trcrn(i,j,nt_qsno+k-1) in CICE5.1.2. What happened to this and where should this be?

**Comment by dabail10** [comment]
Nevermind. This does not seem to be an issue.

**Comment by eclare108213** [comment]
Good, I'm glad you don't think it's an issue.  @njeffery changed this, I believe, fixing a bug.  I don't remember the details at the moment, but if it continues to look suspicious I can track it down.
