### ISSUE TITLE
loft_gnu restarts fail

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/Icepack#204]
ALL restart tests are failing on the loft machine with the gnu compiler.  The scripts are not computing the correct value for the number of timesteps to take in the restart run:

     bash-3.2$ diff icepack_in.2 ../pinto_intel_restart_col_1x1_diag1.fs1/
     7c7
     <     npt            = 0
     ---
     >     npt            = 5124

**Comment by eclare108213** [comment]
@mattdturner or @apcraig Here is the offending line:

      set npt=`grep "npt " icepack_in.1 | grep -oP "\d+" | sort -n | tail -1`

The problem is that the -P option is not available for grep on this laptop.  Can this line be accomplished without it?  I'm not sure what its purpose is here...

       -P, --perl-regexp
              Interpret  PATTERN as a Perl regular expression.  This is highly
              experimental and grep -P may warn of unimplemented features.

**Comment by mattdturner** [comment]
The ``-P`` allows for grep to use the regular expression ``\d+`` to pull the numerical value from the "npt" line in icepack_in.1.  The same functionality can be accomplished multiple different ways:
``set npt=`grep "npt " icepack_in.1 | awk '{print $3}' | sort -n | tail -1` ``
``set npt=`grep "npt " icepack_in.1 | grep -oE "[[:digit:]]+" | sort -n | tail -1` ``
``set npt=`grep "npt " icepack_in.1 | sed "s/[^0-9]*//g" | sort -n | tail -1` ``

I believe that any of those 3 should work, although I'm not sure which one would be best for our cases.

**Comment by eclare108213** [comment]
Scripting is not my forte, so the suggestions are appreciated. @apcraig what’s your preference?


Sent with BlackBerry Work
(www.blackberry.com)

**Comment by eclare108213** [comment]
sed works, and submitted PR #206.  I didn't test the other two options.
