### ISSUE TITLE
make emissivity a namelist variable

### ISSUE THREAD

**Issue by jonbob** [CICE-Consortium/Icepack#211]
It would be very helpful for E3SM if the ice emissivity could be set via a namelist instead of being a parameter. The correct value of this seems to be a research subject and it would help to be able to test different values a bit more easily.

**Comment by apcraig** [comment]
emissivity is a setable parameter in icepack.  it is set by this call,

call icepack_init_parameters(emissivity_in=value)

icepack itself has no namelist.  E3SM should have it's own driver, namelist, and ability to set this parameter in icepack.

We could add emissivity to the icepack driver namelist and/or to the CICE namelist, but that probably would not have an impact on E3SM.  @eclare108213, please let me know if that would be helpful and then which namelist we should use.

**Comment by eclare108213** [comment]
I agree, E3SM can set this up as a namelist parameter regardless of what we do with it.
It would be nice to offer it as a namelist parameter for both Icepack and CICE drivers.  I'd probably put it in forcing_nml.  Open to other suggestions for that.

**Comment by apcraig** [comment]
see #213 for icepack.  same coming soon for CICE.

**Comment by apcraig** [comment]
CICE PR 176.
