### ISSUE TITLE
shortwave_dEdd_set_snow

### ISSUE THREAD

**Issue by dabail10** [CICE-Consortium/Icepack#217]
I have a fix for this in an upcoming pull request. Basically, the fields fsn and hsn should be intent inout instead of out here. They are initialized here:

         fsn        = c0
         hsn        = c0
         rhosnwn(:) = c0
         rsnwn(:)   = c0
         apeffn(n)    = c0 ! for history
         snowfracn(n) = c0 ! for history

         if (aicen(n) > puny) then

            call shortwave_dEdd_set_snow(nslyr,      R_snw,    &
                                         dT_mlt,     rsnw_mlt, &
                                         aicen(n),   vsnon(n), &
                                         Tsfcn(n),   fsn,      &
                                         hs0,        hsn,      &
                                         rhosnwn,    rsnwn)    

Since the variables fsn and hsn are set to zero before the call, these should be intent inout. However, this does change answers. I'm still unclear why this is the case.

**Comment by dabail10** [comment]
Note that this is not answer changing in icepack, but is in CICE.

**Comment by apcraig** [comment]
What PR is this addressed in and do we understand why the answers change?
