### ISSUE TITLE
Bug in temperature_change_mushy

### ISSUE THREAD

**Issue by njeffery** [CICE-Consortium/Icepack#233]
@eclare108213 This is a bugfix for a very infrequent failure in the mushy layer thermodynamics. The mushy temperature change iteration is currently set to a tolerance of ferrmax which is the same as the final energy conservation tolerance.  Every so often, when the temperature change iteration error is very close to ferrmax, the total energy conservation will fail because of round-off level errors in the thickness routine.  We corrected this in mpas_seaice by lowering the tolerance for the iteration to 0.9*ferrmax.  See below.  Lines with + indicated added changes and - indicates deletions.  This is a non BFB change.

We also corrected the diagnostics in the conservation check to properly indicate in this special case if the energy error is due to the temperature change or the thickness change.   This is BFB.

8 src/core_seaice/column/ice_therm_mushy.F90
@@ -523,7 +523,7 @@ subroutine two_stage_solver_snow(nilyr,       nslyr,      &
          ! check if solution is consistent 
          ! surface conductive heat flux should be less than 
          ! incoming surface heat flux
 -         if (fcondtop - fsurfn < ferrmax) then
+          if (fcondtop - fsurfn < 0.9_dbl_kind*ferrmax) then
@@ -576,7 +576,7 @@ subroutine two_stage_solver_snow(nilyr,       nslyr,      &
       ! check if solution is consistent 
       ! surface conductive heat flux should be less than 
       ! incoming surface heat flux
 -      if (fcondtop - fsurfn < ferrmax) then
+      if (fcondtop - fsurfn < 0.9_dbl_kind*ferrmax) then
@@ -842,7 +842,7 @@ subroutine two_stage_solver_nosnow(nilyr,       nslyr,      &
          ! check if solution is consistent 
          ! surface conductive heat flux should be less than 
          ! incoming surface heat flux
-          if (fcondtop - fsurfn < ferrmax) then
+         if (fcondtop - fsurfn < 0.9_dbl_kind*ferrmax) then
@@ -895,7 +895,7 @@ subroutine two_stage_solver_nosnow(nilyr,       nslyr,      &
       ! check if solution is consistent 
       ! surface conductive heat flux should be less than 
       ! incoming surface heat flux
 -      if (fcondtop - fsurfn < ferrmax) then
 +      if (fcondtop - fsurfn < 0.9_dbl_kind*ferrmax) then
15 src/core_seaice/column/ice_therm_vertical.F90
@@ -1837,7 +1837,8 @@ subroutine conservation_check_vthermo(dt,                 &
      real (kind=dbl_kind) :: &
         einp        , & ! energy input during timestep (J m-2)
 -        ferr              ! energy conservation error (W m-2)
  +      ferr        , & ! energy conservation error (W m-2)
  +       ftop            ! surface flux error: fcondtopn-fsurfn
@@ -1883,6 +1884,10 @@ subroutine conservation_check_vthermo(dt,                 &
         call add_warning(warning)
         write(warning,*) fbot,fcondbot
         call add_warning(warning)
+         write(warning,*) 'fsurfn,fcondtopn:'
+        call add_warning(warning)
+       write(warning,*) fsurfn,fcondtopn
+        call add_warning(warning)
@@ -1893,11 +1898,15 @@ subroutine conservation_check_vthermo(dt,                 &
         write(warning,*) 'einter - einit  =', &
              einter-einit
         call add_warning(warning)
+         ftop = c0
+        if (ktherm == 2) then
+            if (fcondtopn > fsurfn) ftop = (fcondtopn-fsurfn)
+         end if
         write(warning,*) 'Conduction Error =', (einter-einit) &
-             - (fcondtopn*dt - fcondbot*dt + fswint*dt)
+             - (fcondtopn*dt - fcondbot*dt + fswint*dt) + ftop*dt
         call add_warning(warning)
         write(warning,*) 'Melt/Growth Error =', (einter-einit) &
 -             + ferr*dt - (fcondtopn*dt - fcondbot*dt + fswint*dt)
 +             + ferr*dt - (fcondtopn*dt - fcondbot*dt + fswint*dt)-ftop*dt

**Comment by dabail10** [comment]
What does the code abort with (before your  fix)? Is this a flux convergence error? How often did you see this error and does this fix eliminate all of the convergence errors? I'm assuming this is also present in CICE5.

**Comment by eclare108213** [comment]
My initial inclination is to postpone fixing this until after the release, because it seems to be extremely rare and the change is not BFB.  MPAS-seaice is running with a VERY old version of the column package (pre Icepack), which @proteanplanet plans to upgrade soon.  I was thinking that he could test this change during that process; there will probably be other changes needed to make Icepack compatible with MPAS-seaice.  However, if this is the source of CESM headaches, then maybe we should get it in sooner.  @dabail10 is there a way to quickly determine whether this helps?

**Comment by duvivier** [comment]
@eclare108213 We are also running with an older version of the code in CESM, so fixing this bug for the Icepack release will not affect our runs. But it's good to know about so we can fix it in our older CICE code used in CESM2. So I'm okay with having @proteanplanet do the tests during the MPAS updating process.

**Comment by apcraig** [comment]
@eclare108213 I agree that it makes sense to defer until after the release and further testing.

**Comment by njeffery** [comment]
I also suspect that it is not climate changing. Another possibility, though, is that with the stricter tolerance, we start to see new convergence failures in the temperature change routine.  We're starting our E3SM coupled bgc simulations  with this fix. I'll let everyone know if we run into problems.


________________________________

**Comment by dabail10** [comment]
Funny. Marika and I were just discussing exactly this change. I will be doing a CESM test with this after AGU.

**Comment by eclare108213** [comment]
@proteanplanet @dabail10 
I'm just pinging this issue again.  It was last commented on in December 2018!  I think we should go ahead and fix it, and certainly we will need to do so for the MPAS/Icepack updates that are planned.  @dabail10 did you test this in CESM, either the 0.9 or 1.1 factor?  @apcraig was there any RASM testing of it?

**Comment by dabail10** [comment]
We have implemented the 1.1 factor in CESM/CICE5. I thought this was already fixed in CICE6?

**Comment by apcraig** [comment]
There was no testing in RASM as far as I know.  If it's fixed in CICE6, then it's in RASM, but I don't think it's been fixed in CICE6.  A grep of ferrmax in icepack_therm_mushy.F90 suggests it has not.

**Comment by proteanplanet** [comment]
The merge of Icepack with E3SM provides an opportunity to check for differences, because the issue does not occur in E3SM to tbe best of my knowledge.

**Comment by eclare108213** [comment]
I think @njeffery found this and fixed it in E3SM to begin with, but it never made its way back to Icepack.  So you're right, the issue does not occur in E3SM any more.

**Comment by njeffery** [comment]
@eclare108213 :  That's correct.

**Comment by eclare108213** [comment]
@dabail10 
Your comment above says that you implemented the 1.1 factor in CESM/CICE5 and tested it.  Was this one of the changes in your port of CESM mods to Icepack?  If not, can we get it in there?

**Comment by dabail10** [comment]
We do have this in CESM/CICE5. I think the alternate solution in CICE6 was used where the convergence is restricted more in the iteration:

    ferr = (efinal - einit) / dt - (fcondtop - fcondbot + fswint - fadvheat)

    lconverged = (dTsf  < dTemp_errmax .and. &
                  dzTsn < dTemp_errmax .and. &
                  dzTin < dTemp_errmax .and. &
                  abs(ferr) < 0.9_dbl_kind*ferrmax)

So, the factor of 0.9 here.

**Comment by eclare108213** [comment]
@njeffery The 0.9*ferrmax factor for lconverged (in the comment immediately above) is in Icepack now.  Is this sufficient to fix the original error, or do we need the factor somewhere else too?  It looks like you might have added it in a lot of places.  

I prefer the fix using the 1.1 factor -- @dabail10 where in the (CESM) code did you put that? 
Thx, e

**Comment by dabail10** [comment]
This fix goes in the final convergence check in icepack_therm_vertical where ferrmax is used.

**Comment by njeffery** [comment]
In the MPAS-O version, I  added the 0.9*ferrmax condition to the mushy two_stage_solver_snow and two_stage_solver_nosnow following the picard solve.  This is done twice in each routine because of the if statement separating the two surface types.

________________________________
From: Elizabeth Hunke ***@***.***>
Sent: Monday, March 15, 2021 10:47:45 AM
To: CICE-Consortium/Icepack
Cc: Jeffery, Nicole; Mention
Subject: [EXTERNAL] Re: [CICE-Consortium/Icepack] Bug in temperature_change_mushy (#233)


@njeffery<https://github.com/njeffery> The 0.9*ferrmax factor for lconverged (in the comment immediately above) is in Icepack now. Is this sufficient to fix the original error, or do we need the factor somewhere else too? It looks like you might have added it in a lot of places.

I prefer the fix using the 1.1 factor -- @dabail10<https://github.com/dabail10> where in the (CESM) code did you put that?
Thx, e
