### ISSUE TITLE
the biogeochemistry forcing

### ISSUE THREAD

**Issue by hzwang1995** [CICE-Consortium/Icepack#239]
I am studying how to run cice 6.0 ,however ,I cannot find some biogeochemistry forcing data ,how can l find them

**Comment by apcraig** [comment]
For general questions about CICE or Icepack, please use the bulletin boards referenced here,

https://github.com/CICE-Consortium/About-Us/wiki/Contacting-the-Consortium

and found here

https://bb.cgd.ucar.edu/forums/cice-consortium-model-development
