### ISSUE TITLE
can we track nonBFB changes easily?

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/Icepack#247]
It would be nice to be able to quickly find all of the PRs that caused non-BFB changes, for both Icepack and CICE.  For example, I included this info in the Icepack 'recent changes' list but didn't include it in the v1.1 release description because I wasn't sure whether these were all of the nonBFB changes.  

- Fix time level inconsistency in transport [#222](https://github.com/CICE-Consortium/Icepack/pull/222) (changes answers)
- Fix intent(inout) in shortwave_dEdd_set_snow [#227](https://github.com/CICE-Consortium/Icepack/pull/227) (changes answers)

We could create a wiki page, which might be difficult to maintain.  Maybe a better solution would be to come up with a unique, searchable string for the PR templates.  GitHub's search box works pretty well for individual repositories.

**Comment by eclare108213** [comment]
Here is a suggestion for the PR templates.  When the PR is merged, we can lock the conversation, which hopefully means that the checkboxes can not be changed after that.  I'm not sure whether the checkboxes will actually work in a template, or if it'll show the square brackets instead.  That might be okay.  The nonBFB text below can be searched for in the GitHub search box.  E.g. search for "[x] Send out release email" in the CICE repository (search in Issues, not Code).

------------------------------------------

[Remove this line and add a short summary]

Developer(s):


Indicate how these code modifications change the answers.  If they are not bit-for-bit, please explain under "Other relevant details" below.
- [ ] bit for bit
- [ ] non-bit-for-bit, roundoff-level changes (requires QC test)
- [ ] non-bit-for-bit, substantial changes (requires QC test)

Link to test results or paste the summary block from the bottom of the testing output:

(for Icepack)
Does this PR create or have dependencies on CICE or any other models? 
(for CICE)
Does this PR create or have dependencies on Icepack or any other models? 
- [ ] yes
- [ ] no


Is the documentation being updated with this PR?  (doc/source, wiki)
- [ ] yes
- [ ] no, a documentation update is not necessary
- [ ] no, it needs to be updated separately


Suggest code reviewers in the column at right.


Other relevant details:

**Comment by apcraig** [comment]
We have updated the PR form and I am going to close this for now.  If others feel it should remain open, please reopen.  Between the PR and test results page, we should be able to figure this out.  Although how easy that might be is open for discussion.
