### ISSUE TITLE
Add water isotopes

### ISSUE THREAD

**Issue by dabail10** [CICE-Consortium/Icepack#248]
We have these in our version of CICE5. So, they would need to be added to both Icepack and CICE. Now that I have a working version of CICE6 in CESM, I am getting started on this.

**Comment by apcraig** [comment]
Just to note, the first PR for water isotopes is #275 and https://github.com/CICE-Consortium/CICE/pull/423.  The main remaining issue is isotope conservation validation (could be science, technical, or diagnostics - TBD).  I will leave this issue open.

**Comment by eclare108213** [comment]
See also #306, for which the isotope conservation issue can be a test case.

**Comment by apcraig** [comment]
Closing, seems to be done.
