### ISSUE TITLE
Add conda environment to run on personal computers

### ISSUE THREAD

**Issue by phil-blain** [CICE-Consortium/Icepack#294]
Mirror CICE-Consortium/CICE#393

**Comment by eclare108213** [comment]
Question:  This command appears in the conda setup instructions for both CICE and Icepack:
`conda env create -f configuration/scripts/machines/environment.yml`
with a comment that "You will need to clone [CICE/Icepack] to run the following command", and then after the command, "This step needs to be done only once."  Does it need to be done only once for either CICE or Icepack on a particular laptop/platform, or once for each of them?

**Comment by apcraig** [comment]
I believe it should be once for Icepack and once for CICE.

**Comment by phil-blain** [comment]
I confirm. The Icepack environment is named `icepack` and the CICE environment is named `cice` (see `environment.yml` in both repos).
