### ISSUE TITLE
update copyright info in code

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/Icepack#297]
change 2019 to 2020 in copyright text, elsewhere
add copyright statement to Icepack interface modules

**Comment by apcraig** [comment]
This has been addressed in #301.  It is also addressed in CICE [#409](https://github.com/CICE-Consortium/CICE/pull/409).

I cannot find a copyright page on the About-Us / Resource Page.  Is there something there?

**Comment by eclare108213** [comment]
There might not be anything in the About-Us repo.  I was thinking of the License files, which are in both the CICE and Icepack repos.  Those are pdfs so I'll probably need to update them (and it looks like I didn't do that last year).

**Comment by apcraig** [comment]
I just had a quick look at the License files, they are pdfs and contain the copyright.  Could we convert these to simple text files so they are easier to edit and maintain in the future?  If @eclare108213 agrees, I'm happy to do that.

**Comment by eclare108213** [comment]
Sure.  I'd like to see what they look like in final form before we commit to this change.  I probably made them pdf originally for the formatting.

**Comment by duvivier** [comment]
Or pdfs because we didn't want it to be easy for users to change.

**Comment by eclare108213** [comment]
I just changed the Icepack License file using Adobe Pro (since I don't have the original on my laptop).  It will be merged with the isotopes PR.  Will do similar for CICE.
