### ISSUE TITLE
Port new snow code from E3SM column physics

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/Icepack#351]
Update the CICE Consortium Icepack code with recent new physics introduced to MPAS-seaice in E3SM, so that the changes will appear back in E3SM when Icepack is set up as a submodule in the sea ice code.

The work is being done in the InteRFACE project's forks of Icepack and CICE, with progress updates in E3SM's JIRA [EC-168].
https://github.com/Arctic-InteRFACE/Icepack

**Comment by apcraig** [comment]
close?

**Comment by eclare108213** [comment]
yes!
