### ISSUE TITLE
missing documentation

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/Icepack#373]
The variable index is empty, there is a problem with the forum link, and also need to clarify where to find the forcing variable information.

Simon Driscoll writes:

> I am a PhD student in the Scale Aware Sea Ice Project ("SASIP" - https://sasip-climate.github.io). My research is focusing on machine learning and data assimilation methods for emulating sea ice thermodynamics. We are looking at the Icepack model, and I can see there is a new version: https://zenodo.org/record/5423061#.YV8Hqy8w2Jk (1.3.0) (I tried the listed CICE consortium link is https://xenforo.cgd.ucar.edu/cesm/forums/cice-consortium.146/ which does not work).
> 
> Icepack 1.3.0 is said to be a "major release update" (including "advanced snow physics") from Icepack 1.2.5. I am looking for a full list of variables that icepack calculates in its model, as well as all fields needed to force the model (i.e. fields required for the forcing data).
> 
> In the documentation for the both the latest model, and the 'master' and 'main' versions, e.g.https://cice-consortium-icepack.readthedocs.io/en/master/icepack_index.htmlthe index of primary variables and parameters is empty. The documentation for the previous version includes in section 6 includes a table of "many" of the symbols/variables used in the model:https://buildmedia.readthedocs.org/media/pdf/cice-consortium-icepack/icepack1.2.5/cice-consortium-icepack.pdf
> 
> I was wondering if there was a complete list of variables in the 1.3.0 model (i.e. that are computed), and a list of variables required for forcing the Icepack model available?

**Comment by dabail10** [comment]
Yes, we had a power outage at the Mesa yesterday and they are still trying to recover. In fact, I was at the office for in person meetings this morning but then came home to do Zoom meetings. I'll try to take a look at this tomorrow.

**Comment by apcraig** [comment]
I think we could close this.  Did anyone get back to Simon?  I see he/she posted something on the forum.

**Comment by dabail10** [comment]
Yes, we have replied on the forum now that it is working again.

**Comment by eclare108213** [comment]
The zenodo weirdness remains, but we could make that a separate issue and include some other issues with zenodo like how datasets are documented there.
