### ISSUE TITLE
Frazil ice temperature limiting

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/Icepack#385]
(in add_new_ice)
https://github.com/CICE-Consortium/Icepack/blob/f6458558b8e7c6bc58eaa8fb33b90b230650f38e/columnphysics/icepack_therm_itd.F90#L1565

The limiting of mush temperature to -0.1C for small salinities (less than 1.844 ppt, I think) "significantly influences year-to-year variations in AMOC" as noted in an E3SM PR where @proteanplanet removed it from add_new_ice and the mct coupler (it also appears in FSD calculations not yet available in E3SM):
https://github.com/E3SM-Project/E3SM/pull/4295

I'm not sure if and how much this matters for coupling approaches different from E3SM's, but it seems worth taking a look.

**Comment by TillRasmussen** [comment]
I/we have not been too focused on the AMOC in our operational setup. But yes it could be interesting to see the effect.

**Comment by dabail10** [comment]
This is interesting. I had not noticed this before. So, we do not use this method for setting the salinity and temperature of frazil. However, I am currently working on code that will do this better.

**Comment by dabail10** [comment]
Sorry, I read this backward initially. The maximum value of the temperature here is set to -0.1C. I wonder if this is motivated to be similar to the "correction" that we make when the shortwave is still penetrating the sea ice at warm temperatures. I guess we don't want it too close to 0C. Has anyone done simulations where this is set to -0.01 or something? I wonder if the liquidus curve gets wacky near 0psu?

I read the E3SM PR comments a bit. I see that the max was removed completely. Is there something in the liquidus computation that sets it to a max of 0C at least?

**Comment by dabail10** [comment]
The E3SM PR indicates this came in in 2013 into CICE. In fact, it was introduced in the 5.1 series.

https://github.com/CICE-Consortium/CICE-svn-trunk/commit/b973671bb0042ce7486feeac46eed1da41df60cc#diff-41cf6794ba4200b839c53531555f0f3998df4cbb01a4d5cb0b94e3ca5e23947d

**Comment by eclare108213** [comment]
Yes.  My question is whether it was in CESM first, or somewhere else.  Just trying to understand the motivation.

**Comment by dabail10** [comment]
This did not come from CESM. This looks like it was part of work that Adrian was doing when coupling CICE to MPAS-O. I received this document from Andrew last year. The document is from 2015. We did not even use CICE5.1 until 2016 I believe.

[frazil_formation_in_mpas-o.pdf](https://github.com/CICE-Consortium/Icepack/files/8005597/frazil_formation_in_mpas-o.pdf)

So, the bottom line is that we can probably remove the upper limit on temperature, but I will have to do some tests in CESM to see if it causes a problem. We can add back in a limit if that causes us a problem. So, I can change this on the Consortium main.

**Comment by eclare108213** [comment]
Okay, thank you.  I'll go back to Adrian!

Can you test it in CESM before changing it in the repo?  I think it should be changed, but I don't want to jump too quickly.  Better to understand what impact it has.

**Comment by dabail10** [comment]
Good plan.

**Comment by eclare108213** [comment]
Fixed in https://github.com/E3SM-Project/Icepack/pull/13
