### ISSUE TITLE
Small bug in temperature_changes_salinity.

### ISSUE THREAD

**Issue by dabail10** [CICE-Consortium/Icepack#388]
In the subroutine temperature_changes_salinity in ice_therm_mushy.F90, the variable snoice should be intent inout.

```
real (kind=dbl_kind), intent(out):: &
         fcondbot    , & ! downward cond flux at bottom surface (W m-2)
         fadvheat    , & ! flow of heat to ocean due to advection (W m-2)
         snoice          ! snow ice formation
```

snoicen is initialized to zero in icepack_therm_vertical.F90, but then this is ignored in temperature_changes_salinity. So, in short one can get accumulation in snoicen when there is no ice. However, this disappears in snoice (the grid cell version) because it is merged using aicen. I only found it because I added snoicen to the history for a separate run.

**Comment by apcraig** [comment]
Looking at this now.  Not sure I understand the problem.  snoice=c0 is one of the first executable lines in temperature_changes_salinity.  Why do we care what it's value is on entry?

**Comment by dabail10** [comment]
I don't think this matters, but I wanted to make sure that it was clear that snoice was initialized locally with intent(out) and that there was not point in initializing before coming into this subroutine. Not a big deal.

**Comment by apcraig** [comment]
OK, I will close this issue.  If anyone thinks there is an outstanding issue, feel free to reopen.
