### ISSUE TITLE
closing/flushing nu_diag at end

### ISSUE THREAD

**Issue by cmbitz** [CICE-Consortium/Icepack#401]
When I compiled with netcdf, I had to add a
close(nu_diag) 
or
flush(nu_diag)
at the end of the program icedrv, otherwise I don't get the last output written to the log file, including the ICEPACK COMPLETED statement, and the stdio would echo "ICEPACK run did not complete".

I tried making it a
call icepack_warnings_flush(nu_diag)
but it didn't work

I'm using my macbook pro with Monterey OSX and gnu compiler. I didn't have this problem until I compiled with netcdf (didn't matter whether I wrote the history file though). With this change all is well getting it to run. 
Thanks, Cecilia

**Comment by eclare108213** [comment]
HI CC,
I also have been having this problem and hadn't fixed it.  Which OSX are you running?  I'm having trouble with Monterey 12.4 on my regular laptop, using the conda environment.  The loaner laptop last week did not have this issue, running OSX Big Sur 11.6.2.  If the close statement is enough to fix it, let's do that...

**Comment by cmbitz** [comment]
I'm running OSX Monterey 12.6. Thanks for entertaining the fix for me, though it is the OS's problem.

**Comment by apcraig** [comment]
I hope this is fixed.  We are flushing and closing all the fileunits at the end of the run.  I am going to close this issue, but please reopen if the problems persist.
