### ISSUE TITLE
Check consistency of snow-transition parameter documentation

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/Icepack#402]
See https://bb.cgd.ucar.edu/cesm/threads/snow-depth-transition-to-bare-sea-ice-icepack.7700/

**Comment by phil-blain** [comment]
See also https://github.com/CICE-Consortium/CICE/issues/635 ?

**Comment by eclare108213** [comment]
Thanks for pointing that one out -- I'll close this and add the forum link to that one.
