### ISSUE TITLE
documentation for calc_dragio and formdrag options

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/Icepack#407]
The current documentation is difficult to find and perhaps confusing.  E.g. calc_dragio is listed in the index and case settings, but isn't mentioned in the text where it's used.  I initially thought it was a variable-drag formulation, but that doesn't seem to be the case.  

The form drag documentation also needs to be reviewed and clarified, if needed.

Is it possible that calc_dragio and formdrag might both be set to .true., and would that be a consistent and meaningful configuration?

**Comment by phil-blain** [comment]
> The current documentation is difficult to find and perhaps confusing. E.g. calc_dragio is listed in the index and case settings, but isn't mentioned in the text where it's used. 

This is addressed in #466.

**Comment by phil-blain** [comment]
> Is it possible that calc_dragio and formdrag might both be set to .true., and would that be a consistent and meaningful configuration?

I guess it would be possible but it would not change the answers that much I think (compared to just `formdrag=.true.`). `dragio` is used to initialize `Cdn_ocn` in `neutral_drag_coeffs`, but then it is overwritten `if aice > p001`. So you get a value of  `dragio` only for these small concentrations.

**Comment by apcraig** [comment]
Should we close this or is there some code clean still to do?

**Comment by eclare108213** [comment]
The `calc_dragio` portion has been addressed but not formdrag.  I think we can close this issue and update the formdrag documentation if/when that parameterization is scrutinized/updated.
