### ISSUE TITLE
investigate impacts of advanced snow physics

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/Icepack#416]
QC runs with the advanced snow physics (including both wind redistribution and wet/dry metamorphosis) are surprisingly different from the default configuration.  See plots in https://github.com/CICE-Consortium/Icepack/pull/415.  These are 5-year standalone CICE runs, gx1 configuration with and without snow options and a couple of bug fixes. 

@njeffery: is the magnitude of the differences what you'd expect?  They seem larger to me than what I remember from my own tests, but we now know there were a number of bugs in both the snow physics and the radiation scheme. 

@dabail10: can standard CESM diagnostics can be created for these runs?  I'd like to explore them (e.g. how much snow is there?)

**Comment by eclare108213** [comment]
Snow thickness results from E3SM indicated that snow aging (metamorphism) increases snow depth in both hemispheres while snow redistribution decreases it (it blows into leads), with the net effect of less snow in the northern hemisphere and more in the southern hemisphere.  The QC results show increased ice thickness in both hemispheres, which would be consistent with increased snow depth in both places.

**Comment by eclare108213** [comment]
I'm not entirely sure what the QC configuration actually includes, e.g. does it use the ocean forcing file?  Does it have monthly output in addition to the daily ice thickness snapshots?  @apcraig please, would you post ice_in here for a baseline case?

**Comment by apcraig** [comment]
The following is ice_in from cice.cb58257857.221126-095037/cheyenne_intel_qcchk_gx1_144x1_medium_qc_qcchk.

[ice_in.txt](https://github.com/CICE-Consortium/Icepack/files/10116490/ice_in.txt)

**Comment by eclare108213** [comment]
From https://github.com/CICE-Consortium/Icepack/pull/415:
> One important comment I might add. The snw cases are starting with the "icdefault" option because restart files are not available. The standard case starts with a proper initial condition. Also, I'm not sure whether these plots are means or something else, maybe someone else knows.

Ah, that helps - different initial conditions will make a big difference.  For QC, the ice thickness data are daily snapshots, but the plots say 'mean ice thickness' so those must be some average of the daily output. Monthly output is not written so we probably can't make CESM diagnostics from these files.

The snow aging table in snow_nml is set to 'test' rather than the regular one - maybe that needs to be fixed in the options files, so that users get the standard configuration rather than a test config.  Also, `oceanmixed_file='unknown_oceanmixed_file'` so deep ocean heat flux convergence in the southern hemisphere is missing,  which also would contribute to thicker ice in all runs.

**Comment by apcraig** [comment]
One more data point, ran a QC for the standard run + icdefault.  This is with snw options off.  3 images follow, standard run + icdefault, current snw options run + icdefault (required), difference.  The runs still fail QC but the differences in the thickness are reduced relative to comparisons with the standard run from a restart file.

![ice_thickness_cheyenne_intel_smoke_gx1_144x1_icdefault_medium_qc qcbaseic](https://user-images.githubusercontent.com/8182814/204666842-75625381-e0fe-4ba0-84b6-d31ce9ba74ae.png)

![ice_thickness_cheyenne_intel_smoke_gx1_144x1_icdefault_medium_qc_snwgrain_snwitdrdg qcsbb](https://user-images.githubusercontent.com/8182814/204666853-c902aab9-7705-4205-a57f-38933bc8029a.png)


![ice_thickness_cheyenne_intel_smoke_gx1_144x1_icdefault_medium_qc qcbaseic_minus_cheyenne_intel_smoke_gx1_144x1_icdefault_medium_qc_snwgrain_snwitdrdg qcsbb](https://user-images.githubusercontent.com/8182814/204666868-5d3e3257-5804-4710-b99b-1ee827c76da0.png)

**Comment by dabail10** [comment]
Here are the plots.

https://webext.cgd.ucar.edu/B1850/b.cesm3_cam058_mom_e.B1850WscMOM.ne30_L58_t061.camdev_cice6.026h/ice/b.cesm3_cam058_mom_e.B1850WscMOM.ne30_L58_t061.camdev_cice6.026h-b.cesm3_cam058_mom_e.B1850WscMOM.ne30_L58_t061.camdev_cice5.026g/yrs1-154/

The 26h run has the advanced snow physics. Basically the snow is much thinner in the Arctic and hence thinner ice. Not as obvious in the southern hemisphere.
