### ISSUE TITLE
Meltpond advection equation

### ISSUE THREAD

**Issue by kshedstrom** [CICE-Consortium/Icepack#452]
My understanding is that the advection equations for the meltponds are naturally written per category. If one does that, one would have to sum up the categories after advection to pass to the Icepack melt ponds - but the first thing they do is unpack the categories. What would you say to having an option to call the melt ponds with the categories already split up? Would an interface that accepts a scalar/vector for the meltpond variables be acceptable?

**Comment by dabail10** [comment]
Hi Kate,

I'm not sure I understand. The apndn and hpndn are in the trcrn tracer array. The advection is done on all of the tracers in trcrn. Then computing the apndn and hpndn is done per category within icepack.

Dave

**Comment by dabail10** [comment]
Sorry, the tracer indices are nt_apnd and nt_hpnd, but these are indeed by category.

**Comment by apcraig** [comment]
You could also try asking this question here, https://bb.cgd.ucar.edu/cesm/forums/cice-consortium.146/

**Comment by kshedstrom** [comment]
Sorry, I must have been remembering an alternate universe. Indeed, I don't see the code I remember.
