### ISSUE TITLE
Inconsistent units in zap_snow_temperature

### ISSUE THREAD

**Issue by kshedstrom** [CICE-Consortium/Icepack#461]
This equation for snow temperature:
```
zTsn = (Lfresh + zqsn/rhos)/cp_ice
```
has Lfresh and zqsn both in J/kg, but the rhos throws things off. Should it instead be:
```
zTsn = (Lfresh + zqsn) / (rhos*cp_ice)
```
???

**Comment by eclare108213** [comment]
Hi @kshedstrom 
The units in some of the comment statements are wrong.  zqsn should be J/m3.  Then with Lfresh in J/kg, rhos in kg/m3 and cp_ice in J/(kg deg) the units in the equation work out correctly.  Issue https://github.com/CICE-Consortium/Icepack/issues/455 has a note to correct the units in the comment statements (see also https://github.com/CICE-Consortium/Icepack/issues/453).  If you notice others that are wrong, please point them out!  Thanks.

**Comment by kshedstrom** [comment]
OK, thanks! We were passing in the wrong thing.
