### ISSUE TITLE
Salinity and enthalpy for new congelation growth.

### ISSUE THREAD

**Issue by dabail10** [CICE-Consortium/Icepack#481]
This code was noted to be an issue my Mathieu Plante (ECCC). This likely overestimates the salt content and enthalpy (set to the same values as sea water) for the new congelation growth (dhi). This results in too much heat being extracted from the ocean mixed layer and hence more frazil production.

https://github.com/CICE-Consortium/Icepack/blob/f6ff8f7c4d4cb6feabe3651b13204cf43fc948e3/columnphysics/icepack_therm_vertical.F90#L1257-L1265

**Comment by dabail10** [comment]
I am re-opening as we did not change the default value of phi_i_mushy here. I feel this goes with the new one-step formulation. Thoughts? Here are some diagnostics from two CESM runs. I would suggest this change is within variability.

https://webext.cgd.ucar.edu/BLT1850/b.e30_beta04.BLT1850.ne30_t232_wgx3.121congel/ice/html/ice/Hemis_seaice_visual_compare_obs_lens.html

@mathieusplante

**Comment by eclare108213** [comment]
What `phi_i_mushy` parameter values were you testing in those plots?

**Comment by dabail10** [comment]
Right. The default value is 0.85 (experiment 121) and the suggested value is 0.45 (121congel).

**Comment by mathieuslplante** [comment]
Hi David,

Yes, I believe this is a good idea. 

I am actually very surprised at the results: I was expecting a larger response, and a significant decrease in ice volume. In particular, if changing to the 2-step lead to a large volume increase, I am puzzled that decreasing the phi_i_mushy by half does not bring the results closer to the standard scheme.

Is it possible to 1. add results from a simulation with the 2-step scheme, and 2. see the contribution terms for the ice growth (congelation and frazil)?

**Comment by dabail10** [comment]
I will work on that. I have to run a new simulation with the two-step scheme.
