### ISSUE TITLE
NBTRCR undefined

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/Icepack#57]
The NAG compiler reports that NBTRCR is undefined in line 297 of ice_zbgc.f90
(issue noted by DMI collaborators)

**Comment by dabail10** [comment]
We have NAG on an NCAR CGD machine.

**Comment by eclare108213** [comment]
Thanks Dave.  This might not be a problem in the newer, columnized version of the code, I’d just like someone to run the test suite there (or at least a run with the debugging flags on) to see if this still turns up as a problem.  But as Tony said, it’s a good idea to test with other compilers anyhow.
e

**Comment by apcraig** [comment]
I've got two compiler warnings that someone should look at from the current code.  I have looked and these look like bugs.  If I knew what to do, I'd fix them.

configuration/driver/icedrv_restart_column.F90:

      call icepack_init_tracer_indices( &
ftn-7212 crayftn: WARNING INIT_ZBGC, File = ../../../../../home/apcraig/cice-consortium/icepack.machcomp/configuration/driver/icedrv_init_column.F90, Line = 1221
  Variable "nbtrcr" is used before it is defined.

      call icepack_init_tracer_flags( &
ftn-7212 crayftn: WARNING INIT_ZBGC, File = ../../../../../home/apcraig/cice-consortium/icepack.machcomp/configuration/driver/icedrv_init_column.F90, Line = 1790
  Variable "tr_bgc_s" is used before it is defined.

**Comment by eclare108213** [comment]
Fixed in PR #119
