### ISSUE TITLE
creating directories

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/Icepack#59]
When scripts create new directories, please have them first check whether the directory exists.  This example came up when I tried to re-run a restart test in a previously used run directory, using a slightly different namelist configuration.

mkdir: cannot create directory `/net/scratch3/eclare/ICEPACK_RUNS/pinto_restart_col_1x1_debug.testrestart/diags_baseline': File exists

Let's keep an eye out for cases when we really do not want to re-use an existing directory, but most of the time it's probably okay for those of us doing manual shortcuts in/around the usually automated test suite.

**Comment by mattdturner** [comment]
What is the desired behavior?  Do you want the scripts to error out if the directory already exists, or just skip the `mkdir` command and continue?

**Comment by eclare108213** [comment]
Just skip and continue.  This is what we did in the old cice scripts:
if !(-d $EXEDIR) mkdir -p $EXEDIR
