### ISSUE TITLE
Documentation chapters

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/Icepack#63]
Fix overall layout of the Icepack documentation:
Table of contents should not be a chapter (but could be chapter 1 if necessary).
Chapter 1 Introduction (or chapter 2)
Chapter 2 Science Guide 
Chapter 3 User Guide 
Chapter 4 Developer Guide
Index of primary variables and parameters (could be chapter 6 if necessary)
Bibliography

**Comment by duvivier** [comment]
This looks like an issue with the PDF generation only, the HTML looks okay to me. Does this agree with what you're seeing Elizabeth?

**Comment by eclare108213** [comment]
No, I think the html shows the same problem.  "Table of Contents:" is the main heading and all of the rest of the doc is in subsections underneath that one.  I think that is coming from the index.rst file, where "Table of Contents:" seems to have a very prominent position.

**Comment by duvivier** [comment]
Elizabeth,
I think I finally got this layout sorted out.
Please check the HTML:
https://duvivier.github.io/Icepack/index.html
And a PDF Generated from the same RST code:
https://github.com/duvivier/Icepack/blob/master/doc/Icepack.pdf
(Note: I will work on the labels of tables and figures next, Issue #67)

**Comment by eclare108213** [comment]
That looks great!

Is there a way to control how much of the outline is shown in the left-hand panel of the html?  The individual html pages are now the subsections rather than whole chapters, and it looks like that’s also limiting the outline.  No worries if this is how it needs to be.   I’d rather time be spent on the contents, at this point, than on the layout, now that you’ve gotten the basic problem fixed.  Thank you!

**Comment by duvivier** [comment]
I noticed that the left-hand panel outline had changed, but I can't figure out at the moment how to make it more extensive. I think we should wait to deal with this until the contents are finalized.

**Comment by duvivier** [comment]
Being addressed with PR #90 and #91
