### ISSUE TITLE
list updates to column physics since cice v5.1.2 release

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/Icepack#64]

**Comment by eclare108213** [comment]
Here's what I found, reading through the svn and github logs.  Anything else?

- created the column package by refactoring CICE
- added warning package for printing diagnostic and error information from within the column physics
- added vertical biogeochemistry, including particulate iron, humic material, modal aerosols, proteins, stationary and mobile phases
- allow biogeochemistry to feed back on sea ice physics through shortwave formulation

bug fixes:
- use net shortwave sum instead of cosine of the zenith angle to limit shortwave calculation for low-/no-light conditions
- corrected unnecessary roundoff errors in delta Eddington shortwave calculation
- define interface temperature in the brine height parameterization
- provide flexibility for tracking frazil ice salt/water in ice or ocean model
- when ponds are very thin, ignore them in the radiation calculation
- ensure fractions of snow, ponds and bare ice add to 1
- wrap pond tracers in conditional blocks in mushy thermodynamics and form drag parameterization
- miscellaneous bug fixes to bgc, hbrine

**Comment by duvivier** [comment]
Fixed by pull request #95
