### ISSUE TITLE
doc wind stress option

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/Icepack#65]
Replace "We have ignored ice motion in u*..." with information about the new option that includes the ice velocity in the wind stress calculation (all turbulent fluxes?), and the circumstances under which it should be used.  This is in the 'Atmosphere' section of the Science Guide.

**Comment by proteanplanet** [comment]
I can take care of this so that it caters to the high-frequency option as well.

**Comment by duvivier** [comment]
Andrew, if you have text for this I can go ahead and include it in a documentation clean up I'm working on. Just let me know.

**Comment by proteanplanet** [comment]
This item is complete to my satisfaction in the documentation and is awaiting as a pull request for Icepack.

**Comment by duvivier** [comment]
Completed with PR #135
