### ISSUE TITLE
add comment about formdrag parameterization to 'known bugs'

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/Icepack#66]

**Comment by proteanplanet** [comment]
Suggested comment:

The form drag parameterization assumes a fixed ridge shape where both the macroscopic ridge porosity and the angle of repose are specified parameters.  One high-resolution coupled model that uses the CICE Column package has been unable to make this parameterization work in its current form. Development of a new, variational approach for ridging is underway that will generate ridge shapes differently from the current parameterization, and is expected to alleviate the reported problem (Roberts, A. et al., 2018).

**Comment by duvivier** [comment]
Fixed in pull request #95
