### ISSUE TITLE
Missing text

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/Icepack#69]
Fix sentences that are missing text in the documentation - look at v5.1.2 doc.
Thermodynamics section:
"... which cannot exceed . "
"... raise its temperature to ."
New temperatures section (BL99):
"... which is held at , and ..."
New temperatures section (mushy):
"... raise the temperature of the sea ice to , including..."
Growth and melting section:
"... of liquid water at . "

**Comment by duvivier** [comment]
Added in the missing degC math text. Not sure why these ones got deleted, but they're fixed in the most recent RST I'm about to PR.
