### ISSUE TITLE
icepack_in default

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/Icepack#71]
Set icepack_in default values as in cice v5.1.2 ice_in and adjust -s options as needed for code coverage.

**Comment by dabail10** [comment]
I can do this now. Cheyenne has been down for the last week and just came back up. Yellowstone is now officially gone, so we should remove it from the machine definitions.

**Comment by dabail10** [comment]
So, the gx1 and gx3 ice_in files in CICE5.1.2 are slightly different. Most of the differences are in setup_nml and tracer_nml. Which ice_in should I follow for icepack_in? Here are the main things:

year_init, npt, kcatbound, tr_FY, tr_pond_lvl versus topo.

Dave

**Comment by eclare108213** [comment]
Good question.  gx3 is our main testing configuration but gx1 is more realistic.  Of the parameters you listed, year_init are npt are case dependent, so we choose them based on the forcing we're using.  kcatbound should be the standard choice from gx1.  tr_FY is just diagnostic, and I'd say turn it off for our purposes.  tr_pond_lvl=T is also standard for gx1.  I'm a little more ambivalent about that one, since there are also good reasons for using topo -- it's kind of a toss-up in my mind with pros and cons either way.  But CESM is using the level-ice ponds, right?  And that's what's in the v5.1.2 gx1 default ice_in, I think, so it would be best to stick with that.

**Comment by dabail10** [comment]
Here are my proposed changes to the icepack_in default:

ice_ic = 'default' (don't we want to start with ice?)
kcatbound = 1
tr_pond_lvl = .true. (This is consistent with the CICE5.1.2 default)
tr_pond_topo = .false. (Leave the remaining tracers off)
bgc_data_dir = 'unknown' (Since we start with the BGC off by default, I think this is better)
precip_units? For the gx1 this is mks, while in Icepack this is mm_per_sec. This is primarily because the default atm_data_type is LYq for gx1 and 'clim' for Icepack.
data_dir = 'unknown' as well

I believe these are the only overlapping namelist variables of concern here.

**Comment by eclare108213** [comment]
ice_ic = 'default' (don't we want to start with ice?)
This is a little confusing in the code.  You can set it to literally anything, as long as restart=F.  It's sent into set_state_var but not used, because the initial conditions when not restarting are specified for each grid cell, individually.  Let's remove it from that subroutine call, and I recommend using 'default' as the icepack_in value.  When restarting, it's set to the file name.

      kcatbound = 1
Is this what's used for cesm?  I've never used anything but kcatbound=0, except for testing.

    bgc_data_dir = 'unknown' (Since we start with the BGC off by default, I think this is better)
    data_dir = 'unknown' as well
bgc_data_dir should be removed from Icepack entirely.  We are putting all forcing data into data_dir, which should be set to the standard path that the tar files on the ftp site unpack into (and include the root directory path that's set in the scripts).  I think @apcraig fixed data_dir already.

      precip_units? For the gx1 this is mks, while in Icepack this is mm_per_sec. This is primarily because the default atm_data_type is LYq for gx1 and 'clim' for Icepack.
precip_units in icepack_in should be appropriate for whichever forcing data set we're using.  mks and mm_per_s are actually the same, so let's use mks.

**Comment by dabail10** [comment]
Actually mks would be m/s while the other is mm/s. Regardless, whatever we decide is the default forcing, then it would correspond to that.

**Comment by eclare108213** [comment]
In CICE, the mks units for precipitation are kg/m/s, which I think works out to mm/s when all the conversion factors are taken into account, and of course assuming a nice round value for density.
e

**Comment by dabail10** [comment]
This is changed in PR4.

**Comment by eclare108213** [comment]
Fixed in PR #98
