### ISSUE TITLE
number of bgc layers?

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/Icepack#72]
The doc currently has this:

``For zbgc with 8 vertical layers:``

    setenv TRBRI  1   # set to 1 for brine height tracer
    setenv TRBGCS 0   # set to 1 for skeletal layer tracers
    setenv TRBGCZ 1   # set to 1 for zbgc tracers
    setenv NBGCLYR 7  # number of zbgc layers

Are there 8 layers when NBGCLYR is 7?

**Comment by duvivier** [comment]
I think this is NOT a typo. Above it in section 2.7.3 it says: "In the case of the skeletal-layer model this is a single layer, while for zbgc there are NBGCLYR+1 vertical layers." And this is consistent with the settings listed below it in the documentation (see here: https://cice-consortium.github.io/Icepack/science_guide/sg_bgc.html#sea-ice-ecosystem)

Nicole, please confirm this. If it is correct, go ahead and close this issue.

**Comment by njeffery** [comment]
Yes.  Not a typo
