### ISSUE TITLE
BGC forcing

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/Icepack#73]
Please add a paragraph describing the ISPOL and N-ICE cases, including forcing fields, time period, and references to the field experiments.

**Comment by duvivier** [comment]
The section to add these is here:
https://cice-consortium.github.io/Icepack/science_guide/sg_bgc.html?highlight=ispol

Once you provide a description and references here, I can add the references to the namelist page where necessary. https://cice-consortium.github.io/Icepack/user_guide/ug_case_settings.html?highlight=ispol . We also need to modify the table since ice_forcing_bgc.F90 has been renamed to icedrv_forcing_bgc.F90.

**Comment by duvivier** [comment]
Nicole, I've added in a bunch of info from you about NICE and ISPOL. A few clarifications are required. In section https://cice-consortium.github.io/Icepack/science_guide/sg_bgc.html?highlight=sil_data_type#sea-ice-ecosystem of the documentation there are listed namelist options sil_data_type and nit_data_type. These were not part of the bgc namelist you provided and I have put up in section https://cice-consortium.github.io/Icepack/user_guide/ug_case_settings.html#table-of-namelist-inputs

Should these both just be bgc_data_type in the namelist? 

Also, so far NICE is only an option for bgc_data_type. Is this correct? The description you provide indicated it should be an option for atm_data_type and ocn_data_type as well.

**Comment by njeffery** [comment]
Hi Alice,


Yes, both sil_data_type and nit_data_type have been changed to bgc_data_type.   NICE and ISPOL are possible options and for atm_data_type/ocn_data_type.


nicole

________________________________

**Comment by eclare108213** [comment]
@njeffery The documentation indicates that the N-ICE ocean forcing is POP output.  Should we call it 'POP' instead of 'NICE', so that it doesn't seem like it's actually measured data?  Is ISPOL ocean data measurements from Ice Station Polarstern or is it also model output?

**Comment by duvivier** [comment]
I have fixed the namelist options with PR #144. I did not change the ocn_data_type to POP but did add a link to the description of the forcing where we clarify that for NICE the ocean data is from a model.

I did not add anything yet about ISPOL data being measurements or model data. This will need to be added when @njeffery gets back to us.

**Comment by njeffery** [comment]
Both ispol and Nice ocean data are from a pop run. This does not include nutrients which are climatology observations from WOA.
n

________________________________

**Comment by duvivier** [comment]
Ok. Just to clarify: do ISPOL and NICE use the same POP run? Do we have documentation or a link to that data? I can add this information to the documentation. Thanks.

**Comment by eclare108213** [comment]
Alice, I suspect that the pop data was pulled from the pop ocean forcing file that we use with the gx1 configuration of stand-alone cice.  It's on the ftp site and @dabail10 created it!  :)  I think you can say something vague, or even just point to that file.  Here's how I've described it in previous publications:

> our simulations are forced with a combination of climatological ocean model output (12 months of surface salinity and slope, currents, and deep heat flux convergence), taken from the CCSM3 1990 control run b30.009 (Collins et al., 2006) and averaged over 20 years into an annual climatology of monthly values

@njeffery please confirm (and tell us which grid points?), but for now let's assume this is correct.  @duvivier please put this in the docs, and if it's wrong we'll change it later.

**Comment by eclare108213** [comment]
@njeffery Nicole, in addition to the question above, please answer this question:  Do the ISPOL and NICE ocean data sets also start on June 16 and April 24, respectively, as do the atmo data sets?  If so, this still needs to be fixed in the code.  (PR #151 fixed the atmo data)

**Comment by duvivier** [comment]
Nicole had said the simulation was run in Jan. 2015, so I didn't add the part about Collins 2006, but otherwise included the info for NICE and ISPOL.

**Comment by eclare108213** [comment]
I'd still like to clarify this information, but we can update the docs later if needed.  I'll take this issue off of the project list.

**Comment by njeffery** [comment]
It's the same pop run and the one that's used for the gx1 stand-alone.

nicole

________________________________

**Comment by duvivier** [comment]
Do we know what grid cells from the POP run the NICE and ISPOL were taken? i/j indices would be helpful.

**Comment by eclare108213** [comment]
The lat-lon values or ranges are given in the documentation, and at least for the N-ICE experiment, the ship was drifting so there was more than one i, j.   The ocean forcing was taken from the Collins et al 2006 referenced run (our gx1 ocean forcing netcdf file) for both test cases, N-ICE and ISPOL.  I think we should just make this clear in the docs and not worry about renaming the files -- they are named for the locations chosen.  The question in PR #160 remains, about whether the dates of the ocean forcing are also offset for these cases, and @njeffery is aware of it.

**Comment by duvivier** [comment]
@eclare108213 I am updating the documentation here for how to use readthedocs before we do the next release and get the DOI process going. Do you want me to add any text to the information about N-Ice and ISPOL section?

**Comment by eclare108213** [comment]
I think you should include the Collins et al 2006 reference (as in the Feb 9 comment above), since that's the run that the ocean forcing climatology was taken from.  Otherwise, leave the N-Ice and ISPOL information as it is, until we find out for sure if it needs to be changed.

**Comment by duvivier** [comment]
Ok, will do!

**Comment by duvivier** [comment]
Added Collins reference as part of Pull Request #187.

**Comment by eclare108213** [comment]
@duvivier has this issue been sufficiently addressed, or are there still outstanding questions?

**Comment by duvivier** [comment]
Yes, this is fixed and I fixed a second typo with pull request #205
