### ISSUE TITLE
documentation of bgc namelist

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/Icepack#74]
Move zbgc namelist options into the namelist table, or create a separate table for it.  This is in the User Guide now.  Replace p1 with 0.1, etc, and remove _dbl_kind from doc table.  Is everything in the 'BGC tuning parameters' table also in namelist?

Also, the current table in the docs looks like it was copied straight out of the code (where it sets defaults).  If that is true, then some of the read values are missing _dbl_kind in the code and should be fixed.

**Comment by duvivier** [comment]
Nicole, I'm going to try and reconcile these issues. I will need you to check this over though once I have it more finalized since I'm not familiar with the BGC code, namelist, etc.

**Comment by njeffery** [comment]
That's great Alice.  Thanks.

I'm working now on committing some code changes to the bgc test cases. Hopefully then I'll have time for the documentation.

Nicole

________________________________

**Comment by duvivier** [comment]
Nicole, please look over the updated documentation I've created here: https://duvivier.github.io/Icepack/

In particular, I need you to look over Table 8 and make sure zbgc_nml variables are correctly entered. Also, do we still need Table 9 or have these options been included in Table 8 now? 

I am aware the units for the zbgc_nml variables in Table 8 are not all formatted properly, but I wanted to make sure the information (names, units, values) was correct before delving into this.

**Comment by njeffery** [comment]
Alice:


Corrections to table 8 under zbgc_nml


1. tr_zero should be tr_zaero

2. in  dEdd_algae description, remove "should not be used when sove_zbgc or skl_bgc are true"

3. in solve_zsal description,  change "therm" to "ktherm"

4. in frazil_scav, change "frail" to "frazil ice"

5. in K_Nit_diatoms, _sp, and _phaeo, and for diatoms, small plankton and phaeocystis, respectively

6. do the same for silicate half saturation,  and iron half saturation

7. from f_don_Am_protein to k_bac_l,  move the word "saccharids" or "lipids" to the end of the description.  For example " saccharids fraction of mortality to DOC" should be "fraction of mortality to DOC saccharids"

8. for lines  algaltype_diatoms to zaerotype_dust4 add to the descriptions of each after "mobile":  i.e.

 algaltype_diatoms would be "mobility type between stationary <-> mobile for diatoms".

The rest are... small plankton, phaeocystis, nitrate, ammonium, silicate, DMSPp, DMPSd, humics, saccharids, lipids, proteins, dissolved iron, particulate iron, black carbon1, black carbon2, dust1, dust2, dust3, and dust4.


n


________________________________

**Comment by duvivier** [comment]
Nicole, Please double check that I've fixed Table 8 to your liking. I added the changes you list as well as updated the units to be correctly formatted. https://duvivier.github.io/Icepack/icepack_3_user_guide.html#table-of-namelist-inputs

Also, for many of the options in Table 8 there is no "recommended value" (last column). Do you want me to add the values listed here (https://cice-consortium.github.io/Icepack/icepack_2_science_guide.html#biogeochemistry  - specifically section 2.2.5.3.2. Vertical “Z” BGC) as the "recommended" values?

Finally, it looks like a good amount of Table 9 overlaps with Table 8 (e.g. T_max). Should we keep both tables?

**Comment by duvivier** [comment]
Nicole, based on some changes I made for another issue Elizabeth opened, you'll find the table to look at here instead:
Table 8
https://duvivier.github.io/Icepack/user_guide/ug_case_settings.html#table-of-namelist-inputs

**Comment by njeffery** [comment]
Hi Alice,


Here's a couple more changes to Table 8, otherwise looks good:


bgc_flux_type  should have two options Jin2006/default  with Jin2006 as suggested.

sil_data_type and nit_data_type have options NICE/ISPOL/clim/default


For recommended values,  using the ones in the bgcISPOL option would be best.


Also, I think Table 9 should remain as is even if some parameters are repeated from Table 8.  There are so many zbgc namelists that separating out the ones to do with biochemistry are helpful for tuning.


Thanks,

nicole

________________________________

**Comment by duvivier** [comment]
Being addressed with PR #90 and #91
