### ISSUE TITLE
which conservation equation?

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/Icepack#75]
In the "Mobile and stationary phases" section,
``The conservation equations are given by Eq. 18 in the CICE v5 documentation with a_pnd a_i replaced by f_b v_in.``
Eq. 18 does not look like the right one.  Is eq. 16 in the Icepack documentation the one you were thinking of? (if the eq numbers change, it's the first equation in the 'tracers that depend on other tracers' section)

**Comment by duvivier** [comment]
Relevant section: https://cice-consortium.github.io/Icepack/science_guide/sg_bgc.html?highlight=mobile%20stationary#mobile-and-stationary

**Comment by njeffery** [comment]
The correct reference is Section2.3.2 equation 2

**Comment by duvivier** [comment]
Addressed by PR #104
