### ISSUE TITLE
365?

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/Icepack#76]
In the reactions section,
``Very long timescales will remove this source/sink term.  The default value is currently set at 3065 days to turn off this dependency.``
Is it really 3065?  Looks like a typo.

**Comment by duvivier** [comment]
I agree this is likely a typo and have changed it in the branch that I'm working on for documentation. Nicole, the section is here: https://cice-consortium.github.io/Icepack/science_guide/sg_bgc.html?highlight=default%20value#reaction-equations . Can you please confirm and close the issue and I will take care of the fix and PR?

**Comment by njeffery** [comment]
Not a typo.  Any large number of days will do.

**Comment by duvivier** [comment]
Got it, thanks!

**Comment by duvivier** [comment]
Fixed with PR #104
