### ISSUE TITLE
clean up index of variables

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/Icepack#80]
Remove anything not in Icepack, and make sure all of the namelist options are included (bullets).

This one is extremely tedious, and I welcome all the help I can get.  We could divide up the alphabet...  I'll take X!

**Comment by dabail10** [comment]
Holy moly. Are you trying to set the gihub issues record for 2017?

**Comment by eclare108213** [comment]
Just making sure you all have something to do on Jan 2!   :)
Seriously, we know we're getting close when documentation rises to the top of the priority list.

**Comment by eclare108213** [comment]
I've tried to assign all of the issues to at least one person.  Those assignments don't seem to be coming through in the email notices, but you can see them here:
https://github.com/CICE-Consortium/Icepack/issues
There are a few unassigned, looking for a volunteer......

**Comment by duvivier** [comment]
I think that I should take the lead on the removal part, even though it's tedious and there are a lot of variables. I'm just afraid dividing it up might result in missing bits and pieces. What thoughts do others have?

**Comment by eclare108213** [comment]
I’d be delighted if you want to take it on.  Let me know if you’d like my help.  Thanks!

**Comment by duvivier** [comment]
Done with PR #106
