### ISSUE TITLE
Remove documentation branch

### ISSUE THREAD

**Issue by duvivier** [CICE-Consortium/Icepack#87]
We need to remove the "documentation" branch from the Icepack repository. It looks like it is stale and was last changed in September. My guess is that it was probably added to the CICE-Consortium accidentally during  PR. However, since the documentation is part of the master branch (RST and PDF) or gh-pages (HTML) I think keeping this branch will cause confusion. I think we should remove it.

**Comment by eclare108213** [comment]
Done.
